# Generated by Django 2.2.7 on 2019-11-26 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='matricula',
            field=models.TextField(max_length=20, unique=True),
        ),
    ]
