# Generated by Django 2.2.7 on 2019-11-27 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_auto_20191127_0144'),
    ]

    operations = [
        migrations.AddField(
            model_name='projeto',
            name='ult_alt',
            field=models.TextField(max_length=100, null=True),
        ),
    ]
