# Generated by Django 2.2.7 on 2019-11-27 18:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0005_projeto_ult_alt'),
    ]

    operations = [
        migrations.AddField(
            model_name='projeto',
            name='data_ult_alt',
            field=models.DateField(default=datetime.date(2019, 11, 27)),
        ),
    ]
