# Generated by Django 2.2.7 on 2019-11-27 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0006_projeto_data_ult_alt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projeto',
            name='data_ult_alt',
            field=models.DateField(null=True),
        ),
    ]
