# Generated by Django 2.2.7 on 2019-11-27 21:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0010_tarefa'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarefa',
            name='projeto',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='usuarios.Projeto'),
            preserve_default=False,
        ),
    ]
