# Generated by Django 2.2.7 on 2019-11-28 15:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0012_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarefa',
            name='categoria',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='usuarios.Categoria'),
            preserve_default=False,
        ),
    ]
