# Generated by Django 2.2.7 on 2019-11-29 00:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0013_tarefa_categoria'),
    ]

    operations = [
        migrations.CreateModel(
            name='Requisito',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.Categoria')),
                ('projeto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.Projeto')),
            ],
        ),
    ]
